### PR TITLE
Fix regression of optional profile picture

### PR DESCRIPTION
**Pull request by Hespe**
Hi,

last year the profile picture was made optional.
It looks like there was an regression in #4. 
Currently leaving out the \cvprofilepic command leads to a compilation error.

This change fixes the regression and makes the profile picture optional again.

### CODE REVIEW

**Comment by PandaScience** [comment]
Great. Thanks for reporting and providing a PR!
